services:
  app:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "8080:80"   # Host 8080 -> Container 80 (nginx)
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
